### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [bambinos/bambi#203]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.2.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary bambi -w /tmp/ext bambi==0.2.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting bambi==0.2.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/2d1/521905f282992/bambi-0.2.0.tar.gz (50 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ufip2m_p/bambi/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ufip2m_p/bambi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ufip2m_p/bambi/pip-egg-info
         cwd: /tmp/pip-wheel-ufip2m_p/bambi/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ufip2m_p/bambi/setup.py", line 45, in <module>
        install_requires=get_requirements(),
      File "/tmp/pip-wheel-ufip2m_p/bambi/setup.py", line 19, in get_requirements
        with codecs.open(REQUIREMENTS_FILE) as buff:
      File "/usr/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-ufip2m_p/bambi/requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by aloctavodia** [comment]
Hi @thatch, thanks for you help. Could you help me understand why even when these files are missing, bambi is still pip installable?

**Comment by thatch** [comment]
The is only seen when using `--no-binary` to force using the sdist.  When you generated the wheel from the repo, the files were present, but you should also be able to generate a wheel from only what's in the sdist (which is what the log in the PR shows now)
