### ISSUE TITLE
Use a sparse matrix for group specific effects

### ISSUE THREAD

**Issue by hans-ekbrand** [bambinos/bambi#545]
Background: I recently observed large RAM usage on a model, and opened an issue on pymc discourse, and in that thread Tomás Capretto responded:

"On the other hand, Bambi relies on formulae to generate design matrices, which turns out to generate a regular matrix for group-specific effects. In this case, it’s a very large matrix with almost all zeros, so a sparse matrix would have been better. So I think this explains the large memory comsumption. It is something we still need to improve on our end. However, this matrix is not directly used in the PyMC model, we use slicing to select only non-zero values."

Today this issue hit me again, and this time the RAM requirements were absurd:

```
my_model = bmb.Model("deprived.of.education ~ (sex|country) +    (sex|cluster.id.unique) + per.cent.muslim.in.country*sex*gdp.log + per.cent.hindu.in.country*sex*gdp.log + per.cent.muslim.in.cluster*sex*wealth.at.cluster.level + per.cent.hindu.in.cluster*sex*wealth.at.cluster.level + wealth * sex * religion + urbrur", df, family="bernoulli", dropna=True)

Automatically removing 739811/2772473 rows from the dataset.
Unexpected error while trying to evaluate a Variable. <class 'numpy.core._exceptions._ArrayMemoryError'>

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\hanse\miniconda3\lib\site-packages\bambi\models.py", line 147, in __init__
    self._design = design_matrices(formula, data, na_action, 1, extra_namespace)
  File "C:\Users\hanse\miniconda3\lib\site-packages\formulae\matrices.py", line 523, in design_matrices
    design = DesignMatrices(description, data, env)
  File "C:\Users\hanse\miniconda3\lib\site-packages\formulae\matrices.py", line 54, in __init__
    self.model.eval(data, env)
  File "C:\Users\hanse\miniconda3\lib\site-packages\formulae\terms\terms.py", line 1261, in eval
    term.set_data(encoding)
  File "C:\Users\hanse\miniconda3\lib\site-packages\formulae\terms\terms.py", line 665, in set_data
    self.factor.set_data(True)  # Factor is a categorical term that always spans the intercept
  File "C:\Users\hanse\miniconda3\lib\site-packages\formulae\terms\terms.py", line 468, in set_data
    component.set_data(spans_intercept_)
  File "C:\Users\hanse\miniconda3\lib\site-packages\formulae\terms\variable.py", line 109, in set_data
    self.eval_categoric(self._intermediate_data, spans_intercept)
  File "C:\Users\hanse\miniconda3\lib\site-packages\formulae\terms\variable.py", line 166, in eval_categoric
    value = self.contrast_matrix.matrix[x.codes]
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 857. GiB for an array with shape (2032662, 113158) and data type int32
```

There are two random slopes in the model, the first grouping factor has 88 levels, and the second grouping factor has 145861 levels, so the model in itself is not very big. I am happy to provide the data if it is useful.

**Comment by humana** [comment]
I'm having the same problem, RAM usage explodes to over 120gb.  How difficult would it be for Bambi to use sparse matrices?

**Comment by tomicapretto** [comment]
@humana, apologies for the slow response.

It's not something you can change from the outside, but something we have to change at the formulae level first.
Unfortunately, I don't think it can happen very soon.

Is translating the model to PyMC an option for you? Maybe I can help.

**Comment by tomicapretto** [comment]
I'm finally working on this issue. @hans-ekbrand @humana do you have a dataset I can use to see this behavior? I'll work with simulated ones, but I want to try also other that look more real. Thanks!

**Comment by humana** [comment]
That is awesome!  I've added a minimal example from the dataset / model that we use, minus some priors. It takes about 90gb of RAM on my machine to build the model. Let me know if I can help any further. 

[testsparse.zip](https://github.com/user-attachments/files/24099636/testsparse.zip)

**Comment by tomicapretto** [comment]
@humana, does it take 90 gb of RAM to _build_ or _fit_ the model? I'm seriously impressed by the size of this thing, I was not expecting users to be battle-testing my code this seriously haha.

Nevertheless, it is sampling now and taking ~ 20 Gb per process (your 90 Gb are the total)?

As far as I see, group specific effects are not the problem here, in terms of the size of their design matrix (which is my I'm resolving with my updates). However, you do have a seriously big design matrix for the common effects. I think this one is quite sparse in this case (but it's not something we can assume for most common effects design matrices).

Have you considered writing this model directly in PyMC? You could reduce the bulk of the computation to one or two (quite big) dot products and I think it can sample much faster.

**edit**

if you wan to try this your own, you can do

```shell
pip install git+https://github.com/tomicapretto/bambi@sparse-random-effects
```

to install Bambi from the branch I'm updating it.

**Comment by zwelitunyiswa** [comment]
I am interested to see what the lift is from the new PR on the same model.

Z.

**Comment by tomicapretto** [comment]
> I am interested to see what the lift is from the new PR on the same model.
> 
> Z.
> […](#)

@zwelitunyiswa do you think you have an example where you can try it? So far, the only differences you should see are:

1. You can now create models with hierarchical terms that you were not able to create before because of memory errors.
2. A smaller usage of RAM when _creating_ Bambi models that involve hierarchical terms (not when sampling)

Under the hood, we're still creating the PyMC model in the same way. My next step is to allow users to choose between a mat-mul or advanced indexing (what we do now). You can expect a sparse matrix multiplication to make a difference when the number of observations and number of groups are large.

**Comment by zwelitunyiswa** [comment]
> > I am interested to see what the lift is from the new PR on the same model.
> > Z.
> > […](#)
> 
> [@zwelitunyiswa](https://github.com/zwelitunyiswa) do you think you have an example where you can try it? So far, the only differences you should see are:
> 
> 1. You can now create models with hierarchical terms that you were not able to create before because of memory errors.
> 2. A smaller usage of RAM when _creating_ Bambi models that involve hierarchical terms (not when sampling)
> 
> Under the hood, we're still creating the PyMC model in the same way. My next step is to allow users to choose between a mat-mul or advanced indexing (what we do now). You can expect a sparse matrix multiplication to make a difference when the number of observations and number of groups are large.

@tomicapretto I think I do actually. I will only be able to try it this weekend though. 15 thousand individuals in 50 states with > 90 observations each.

**Comment by tomicapretto** [comment]
@zwelitunyiswa, perfect! Let me know if you need any help.

**Comment by humana** [comment]
> [@humana](https://github.com/humana), does it take 90 gb of RAM to _build_ or _fit_ the model? I'm seriously impressed by the size of this thing, I was not expecting users to be battle-testing my code this seriously haha.
> 
> Nevertheless, it is sampling now and taking ~ 20 Gb per process (your 90 Gb are the total)?
> 
> As far as I see, group specific effects are not the problem here, in terms of the size of their design matrix (which is my I'm resolving with my updates). However, you do have a seriously big design matrix for the common effects. I think this one is quite sparse in this case (but it's not something we can assume for most common effects design matrices).
> 
> Have you considered writing this model directly in PyMC? You could reduce the bulk of the computation to one or two (quite big) dot products and I think it can sample much faster.
> 
> **edit**
> 
> if you wan to try this your own, you can do
> 
> pip install git+https://github.com/tomicapretto/bambi@sparse-random-effects
> to install Bambi from the branch I'm updating it.

I will give this branch a try and let you know.

Yes the issue I was having is that it consumes 90gb to build the model, i.e. bambi.Model(...).  To actually fit is not so much a problem since I fit it on 4xA100 GPUs with the Blackjax sampler, which takes about 4 hours for 2000 tune and 3000 draws on 4 chains. Everything converges nicely and RHat <= 1.01 for everything.

When you say "writing this model directly in PyMC" what exactly do you mean? I'm sorry but I'm not familiar with PyMC directly, I came to use Bambi from using R previously with the lmer library. I liked the fact that that you could specify the model formula like you do in R and also that it had the predict method and the interpret library.  What would one "lose" by doing it directly in PyMC? Or can one maybe just build/fit the model in PyMC and then continue using Bambi with the fitted model? The main issue is just that I need to serialize the fitted model, and then I need to re-load it an inference time to call predict, since this model is used for online prediction, not interpretation.  To re-load a Bambi model requires to build it again (bambi.Model(...)), with the same formula, and thus each inference node also requires 90gb.

**Comment by humana** [comment]
@tomicapretto I've tried your branch and the good news: RAM usage is down to about 17GB so that is amazing! I did however get an error when calling predict after fitting:

```
TypeError                                 Traceback (most recent call last)
Cell In[7], line 1
----> 1 preds = model.predict(idata, data=pred_row, inplace=False)
      2 print(preds.posterior)

File ~/projects/tmp/sparse_features/.venv/lib/python3.11/site-packages/bambi/models.py:931, in Model.predict(self, idata, kind, data, inplace, include_group_specific, sample_new_groups, random_seed)
    928     idata = deepcopy(idata)
    930 # Populate the posterior in the InferenceData object with the likelihood parameters
--> 931 idata = self._compute_likelihood_params(
    932     idata, data, include_group_specific, sample_new_groups
    933 )
    935 # Only if requested predict the predictive distribution
    936 if kind == "response":

File ~/projects/tmp/sparse_features/.venv/lib/python3.11/site-packages/bambi/models.py:1081, in Model._compute_likelihood_params(self, idata, data, include_group_specific, sample_new_groups)
   1079 for name, component in self.distributional_components.items():
   1080     var_name = component.alias if component.alias else name
-> 1081     means_dict[var_name] = component.predict(
   1082         idata, data, include_group_specific, hsgp_dict, sample_new_groups
   1083     )
   1085     # Drop var/dim if already present. Needed for out-of-sample predictions.
   1086     if var_name in idata.posterior.data_vars:

File ~/projects/tmp/sparse_features/.venv/lib/python3.11/site-packages/bambi/model_components.py:162, in DistributionalComponent.predict(self, idata, data, include_group_specific, hsgp_dict, sample_new_groups)
    157     linear_predictor += self.predict_common(
    158         posterior, data, in_sample, to_stack_dims, design_matrix_dims, hsgp_dict
    159     )
    161 if self.design.group and include_group_specific:
--> 162     linear_predictor += self.predict_group_specific(
    163         posterior, data, in_sample, to_stack_dims, design_matrix_dims, sample_new_groups
    164     )
    166 # Sort dimensions
    167 linear_predictor = linear_predictor.transpose(*linear_predictor_dims)

File ~/projects/tmp/sparse_features/.venv/lib/python3.11/site-packages/xarray/core/_typed_ops.py:772, in DataArrayOpsMixin.__iadd__(self, other)
    771 def __iadd__(self, other: DaCompatible) -> Self:  # type:ignore[misc]
--> 772     return self._inplace_binary_op(other, operator.iadd)

File ~/projects/tmp/sparse_features/.venv/lib/python3.11/site-packages/xarray/core/dataarray.py:4923, in DataArray._inplace_binary_op(self, other, f)
   4921 try:
   4922     with self.coords._merge_inplace(other_coords):
-> 4923         f(self.variable, other_variable)
   4924 except MergeError as exc:
   4925     raise MergeError(
   4926         "Automatic alignment is not supported for in-place operations.\n"
   4927         "Consider aligning the indices manually or using a not-in-place operation.\n"
   4928         "See https://github.com/pydata/xarray/issues/3910 for more explanations."
   4929     ) from exc

File ~/projects/tmp/sparse_features/.venv/lib/python3.11/site-packages/xarray/core/_typed_ops.py:1200, in VariableOpsMixin.__iadd__(self, other)
   1199 def __iadd__(self, other: VarCompatible) -> Self:  # type:ignore[misc]
-> 1200     return self._inplace_binary_op(other, operator.iadd)

File ~/projects/tmp/sparse_features/.venv/lib/python3.11/site-packages/xarray/core/variable.py:2465, in Variable._inplace_binary_op(self, other, f)
   2463     raise ValueError("dimensions cannot change for in-place operations")
   2464 with np.errstate(all="ignore"):
-> 2465     self.values = f(self_data, other_data)
   2466 return self

TypeError: operand type(s) all returned NotImplemented from __array_ufunc__(<ufunc 'add'>, '__call__', array([[[11.58101861, 11.62652765, 11.59071383, 11.57339161,
         11.57339161, 11.57339161, 11.57339161, 11.57339161,
         11.57339161, 11.57339161]]]), <COO: shape=(1, 1, 10), dtype=float64, nnz=10, fill_value=0.0>, out=(array([[[11.58101861, 11.62652765, 11.59071383, 11.57339161,
         11.57339161, 11.57339161, 11.57339161, 11.57339161,
         11.57339161, 11.57339161]]]),)): 'ndarray', 'COO', 'ndarray'
```

**Comment by humana** [comment]
@tomicapretto The fix seems simple enough. It's just cause you can't do in-place addition between a dense numpy array and a COO sparse matrix:

```diff --git a/bambi/model_components.py b/bambi/model_components.py
index 1234567..abcdef0 100644
--- a/bambi/model_components.py
+++ b/bambi/model_components.py
@@ -159,7 +159,7 @@ class DistributionalComponent:
         )
 
         if self.design.group and include_group_specific:
-            linear_predictor += self.predict_group_specific(
+            linear_predictor = linear_predictor + self.predict_group_specific(
                 posterior,
                 data,
                 in_sample,
````

Seems to fix the predict call.

**Comment by tomicapretto** [comment]
@humana it's great to see those good news and thanks for the fix!

**Comment by tomicapretto** [comment]
@humana what version of xarray were you using? Asking since that is not an issue for me, but I see you're under python 3.11 and maybe you're using an older version of xarray (or some other dependency).

What's happening under the hood is that we're doing:

```python
u = xr.DataArray(u, dims=u_dims)
Z = xr.DataArray(sparse.COO.from_scipy_sparse(Z), dims=design_matrix_dims)
out = xr.dot(Z, u)
```

For me, `out` is a `xarray.DataArray` that already contains a dense numpy array in it.

I'm on the latest release of xarray.

```python
print(xr.__version__)
# 2025.12.0
```

---

Update: If you can install from the mentioned branch again, it should work without any other change.

**Comment by GStechschulte** [comment]
Hey @humana it is nice to see you find the interpret sub-module valuable. Is there any functionality you wish it had? Or is there anything about the API that is not clear? Thanks!

**Comment by tomicapretto** [comment]
@zwelitunyiswa if you have an example where you have a lot of rows and group-specific effects, you could try:

```python
bmb.config.SPARSE_DOT = True
model = ...
idata = model.fit()
```

Just note that it doesn't yet work with PyMC's numba backend or nutpie. There's something still to be figured out in PyTensor about numba and sparse data structures.
